#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: deblur # 수정 했음
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 50
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1 # 수정 했음
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /media/hdd0/OSH/Task1/train_data/GT # 수정 했음
    dataroot_LQ: /media/hdd0/OSH/Task1/train_data/LQ # 수정 했음

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 128
    LR_size: 128
    use_flip: false
    use_rot: false
    color: Grayscale # 수정 했음
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /media/hdd0/OSH/Task1/validation_data/GT # 수정 했음
    dataroot_LQ: /media/hdd0/OSH/Task1/validation_data/LQ # 수정 했음


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1 # 수정 했음
    out_nc: 1 # 수정 했음
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3